name: Bump Homebrew accs formula

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v3.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tap: ShotaKashihara/homebrew-tap
          formula: accs
