name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container: swift:5.3
    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Test
      run: make test
